# Generated by Django 5.1.5 on 2025-01-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='University',
            new_name='Universities',
        ),
    ]
