# Generated by Django 5.1.5 on 2025-01-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_rename_university_universities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universities',
            name='shortname',
        ),
        migrations.AddField(
            model_name='universities',
            name='perCapitaFoodEmissions',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='universities',
            name='percentAnimalBased',
            field=models.FloatField(default=-1),
        ),
    ]
