# Generated by Django 5.1.5 on 2025-01-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_remove_universities_shortname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='fullyVeganStation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='universities',
            name='labelsDescriptionsRating',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='universities',
            name='overallScore',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='universities',
            name='pbculinaryTraining',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='universities',
            name='plantBasedCommitments',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='universities',
            name='plantBasedDairy',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='universities',
            name='sustainableDiningResources',
            field=models.IntegerField(default=-1),
        ),
    ]
