# Generated by Django 5.1.5 on 2025-01-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_universities_fullyveganstation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='sustainableDiningResources',
            field=models.IntegerField(default=-1),
        ),
    ]
