# Generated by Django 5.1.5 on 2025-01-31 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_alter_universities_sustainablediningresources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universities',
            old_name='fullyVeganStation',
            new_name='detailsOverview',
        ),
    ]
