# Generated by Django 5.1.5 on 2025-02-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_rename_fullyveganstation_universities_detailsoverview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='detailsOverview',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='universities',
            name='pbculinaryTraining',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='universities',
            name='plantBasedDairy',
            field=models.TextField(default='none'),
        ),
    ]
