# Generated by Django 5.1.5 on 2025-02-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_alter_universities_detailsoverview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universities',
            name='labelsDescriptionsRating',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='pbculinaryTraining',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='perCapitaFoodEmissions',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='percentAnimalBased',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='plantBasedCommitments',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='plantBasedDairy',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='sustainableDiningResources',
        ),
        migrations.AddField(
            model_name='universities',
            name='animal_based_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='culinary_training',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='default_veg_program',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='formal_commitments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='labeling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='meatless_monday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='naming',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='per_capita_emissions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='plant_dairy_options',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='plant_desserts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='promotional_materials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='universities',
            name='reduction_animal_based_1yr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='reduction_animal_based_5yr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='salad_protein',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='student_satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='sustainable_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='universities',
            name='transition_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='universities',
            name='vegan_meals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='vegan_station',
            field=models.BooleanField(default=False),
        ),
    ]
