# Generated by Django 5.1.5 on 2025-02-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_remove_universities_labelsdescriptionsrating_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Universities',
            new_name='University'
        ),
       
    ]
