# Generated by Django 5.1.5 on 2025-02-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0010_remove_university_per_capita_emissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='overallGrade',
            field=models.CharField(default='B', max_length=255),
        ),
    ]
