# Generated by Django 5.1.5 on 2025-02-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0011_alter_university_overallgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='recent_changes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='sustainability_guidebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='animal_based_percentage',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
