# Generated by Django 5.1.5 on 2025-02-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0012_university_recent_changes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='animal_based_percentage',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='plant_breakfast_options',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='salad_protein',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
