# Generated by Django 5.1.5 on 2025-02-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0013_alter_university_animal_based_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='animal_based_percentage',
            field=models.FloatField(blank=True, default=79, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='overallScore',
            field=models.IntegerField(default=0),
        ),
    ]
