# Generated by Django 4.2.19 on 2025-02-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0014_alter_university_animal_based_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='formal_commitments',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
