# Generated by Django 4.2.19 on 2025-03-06 22:38

from django.db import migrations, models
import django.db.models.deletion
import leaderboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0016_alter_university_labeling_alter_university_naming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='detailsOverview',
            field=models.TextField(default='Details Overview Goes Here'),
        ),
        migrations.CreateModel(
            name='UniversityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=leaderboard.models.upload_to_university_images)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='leaderboard.university')),
            ],
        ),
    ]
