# Generated by Django 4.2.19 on 2025-03-17 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0017_alter_university_detailsoverview_universityimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='leaderboard.university')),
            ],
        ),
    ]
