# Generated by Django 4.2.19 on 2025-03-24 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0020_alter_universitytestimonial_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitytestimonial',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='universitytestimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='universitytestimonial',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='universitytestimonial',
            name='role',
            field=models.CharField(default='Student', max_length=255),
        ),
        migrations.AlterField(
            model_name='universitytestimonial',
            name='stars',
            field=models.FloatField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
