# Generated by Django 4.2.19 on 2025-04-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0021_universitytestimonial_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitytestimonial',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
