# Generated by Django 4.2.19 on 2025-04-06 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaderboard', '0022_alter_universitytestimonial_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('name_permission', models.BooleanField(default=False)),
                ('photo_permission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('student', 'Current Student'), ('alumni', 'Alumni'), ('faculty', 'Faculty/Staff'), ('other', 'Other')], max_length=20, verbose_name='Your Connection to the University')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
