# Generated by Django 4.2.19 on 2025-04-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0024_review_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name_permission',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo_permission',
            field=models.BooleanField(default=True),
        ),
    ]
